<?php
declare(strict_types=1);


use Drupal\jw_preload as _;
use function Functional\each as each_;
use function Functional\map;
use function Functional\pluck;
use function Functional\reindex;
use RightThisMinute\Drupal\extra_log as log;
use RightThisMinute\JWPlatform\Management\v2\request\WebhooksEventBody;


/**
 * Implements hook_init().
 */
function jw_preload_init () : void
{
  $current_path = current_path();

  if (path_is_admin($current_path))
    return;

  $preloaded = _\queue_metadata_for_preload_by_path($current_path);

  # Make relevant metadata available via global Drupal JS object.
  $metadata = reindex($preloaded, function($p){ return $p->media_id; });
  $metadata = map($metadata, function($m){ return unserialize($m->value); });

  if (count($metadata) === 0)
    return;

  drupal_add_js(['jw_preload' => ['metadata' => $metadata]], 'setting');
}


/**
 * Implements hook_cron_queue_info().
 */
function jw_preload_cron_queue_info () : array
{
  return
    [ _\PRELOAD_QUEUE =>
      [ 'worker callback' =>
        'Drupal\jw_preload\process_to_preload_queue_item' ]];
}


/**
 * Implements hook_entity_insert().
 */
function jw_preload_entity_insert (stdClass $entity, string $type) : void
{
  $uri = entity_uri($type, $entity);

  if ($uri === null || !isset($uri['path']))
    return;

  _\queue_metadata_for_preload_by_path($uri['path'], $entity);
}


/**
 * Implements hook_entity_update().
 */
function jw_preload_entity_update (stdClass $entity, string $type) : void
{
  $uri = entity_uri($type, $entity);

  if ($uri === null || !isset($uri['path']))
    return;

  _\queue_metadata_for_preload_by_path($uri['path'], $entity);
  _\clear_page_cache_by_paths([$uri['path']]);
}


/**
 * Implements hook_entity_delete().
 */
function jw_preload_entity_delete (stdClass $entity, string $type) : void
{
  try {
    [$id] = entity_extract_ids($type, $entity);
  }
  catch (\Exception $exn) {
    log\error
      ( 'jw_preload'
      , 'Failed getting IDs of %type entity: %exn'
      , [ '%type' => $type
        , '%exn' => $exn->getMessage()
        , 'entity' => $entity
        , 'exception' => $exn ]);
    return;
  }

  # Delete media relations for this entity
  $relations = _\media_relations_by_entity($type, (int)$id);
  each_($relations, function(_\MediaRelation $rel){
    _\delete_media_relation($rel->media_id, $rel->path);
  });

  # Clear out metadata for related media if these were the last relations.
  $media_ids = pluck($relations, 'media_id');
  _\delete_metadata_by_media_ids_without_relation($media_ids);
}


/**
 * Implements hook_jw_webhooks_register().
 */
function jw_preload_jw_webhooks_register () : array
{
  return _\JW_WEBHOOKS_EVENTS;
}


/**
 * Implements hook_jw_webhooks_receive().
 */
function jw_preload_jw_webhooks_receive (WebhooksEventBody $event) : void
{
  # Don't handle events we haven't registered for.
  if (!in_array($event->event, _\JW_WEBHOOKS_EVENTS))
    return;

  if (in_array($event->event, ['media_reuploaded', 'media_deleted'])) {
    # No point in trying to preload metadata for any of these events. Either
    # we need to wait on transcoding or the media just doesn't exist anymore.
    _\clear_preloaded_metadata_by_media_id($event->media_id);
    return;
  }

  # For all other events, we can just (re-)preload the metadata now.
  _\preload_metadata_by_media_ids_with_relations([$event->media_id]);
}
