<?php
declare(strict_types=1);


use Drupal\jw_preload as _;
use function Functional\select;
use RightThisMinute\Drupal\extra_log as log;


/**
 * Implements hook_init().
 */
function jw_preload_init () : void
{
  $current_path = current_path();

  [$entity, $entity_type, $entity_id] =
    _\entity_type_and_id_by_path($current_path);

  # Grab media IDs of videos that would show up on this path.
  $media_ids = module_invoke_all
    ( 'jw_preload_register_media_ids'
    , $entity
    , $entity_type
    , $entity_id );

  if (count($media_ids) === 0) {
    # Clear out existing references to this path since it seems nobody cares
    # about it anymore.
    $media_ids = _\media_ids_by_path($current_path);

    _\delete_metadata_by_media_ids($media_ids);
    _\delete_media_relations_by_path($current_path);

    return;
  }

  # Record relations not previously recorded.
  $existing = _\media_relations_by_path($current_path);
  $new_media_ids = select($media_ids, function($media_id)use($existing){
    return !isset($existing[$media_id]);
  });

  try {
    _\add_media_relations($new_media_ids, $current_path, $entity_type, $entity_id);
  }
  catch (Exception $exn) {
    log\error
      ( 'jw_preload'
      , 'Failed saving media relations: %exn'
      , [ '%exn' => $exn->getMessage()
        , 'media IDs' => $new_media_ids
        , 'path' => $current_path
        , 'entity type' => $entity_type
        , 'entity ID' => $entity_id
        , 'exception' => $exn ]);
  }

//  $preloaded =
}
